server:
  port: 60001
  servlet:
    context-path: /fundf10

---

spring:
  application:
    name: fundf10

swagger:
  enable: true
  host: localhost
---
# datasource config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filter:
        wall:
          config:
            delete-allow: true
            drop-table-allow: false
          enabled: true
        log4j:
          enabled: true
      filters: stat,wall,log4j
      initial-size: 10
      max-active: 100
      max-pool-prepared-statement-per-connection-size: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      min-idle: 10
      pool-prepared-statements: true
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1 FROM DUAL
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/fund?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456

# mybatis config
mybatis:
  configuration:
    default-statement-timeout: 60
    map-underscore-to-camel-case: true

# pagehelper config
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  # PageHelper 分页默认页数
  default-pageNum: 1
  # PageHelper 分页默认每页数量
  default-pageSize: 10

fundf10:
  # 拦截器配置
  interceptor-config:
    # 日志拦截器
    log-config:
      enabled: true
      response:
        # 是否开启输出响应日志
        enabled: true
      include-path: /**
      exclude-path: /swagger-ui.html,/swagger-resources/**,/csrf,/webjars/**,/error
