package com.lym.domain;

import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import lombok.Data;
import lombok.ToString;
import lombok.experimental.Accessors;

/**
 * Table Name : t_fund_info
 * Created by Tustrip Mybatis Generator on 2021/02/14
 */
@Data
@Accessors(chain = true)
@ToString
public class FundInfo {
    @ApiModelProperty("基金代码")
    private String fundCode;

    @ApiModelProperty("基金名称")
    private String fundName;

    @ApiModelProperty("基金类型")
    private String fundType;

    @ApiModelProperty("添加时间")
    private LocalDateTime addTime;

    @ApiModelProperty("修改时间")
    private LocalDateTime updateTime;

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table t_fund_info
     */
    public enum Column {
        fundCode("fund_code", "fundCode", "VARCHAR", false),
        fundName("fund_name", "fundName", "VARCHAR", false),
        fundType("fund_type", "fundType", "VARCHAR", false),
        addTime("add_time", "addTime", "TIMESTAMP", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false);

        private static final String BEGINNING_DELIMITER = "\"";

        private static final String ENDING_DELIMITER = "\"";

        private final String column;

        private final boolean isColumnNameDelimited;

        private final String javaProperty;

        private final String jdbcType;

        public String value() {
            return this.column;
        }

        public String getValue() {
            return this.column;
        }

        public String getJavaProperty() {
            return this.javaProperty;
        }

        public String getJdbcType() {
            return this.jdbcType;
        }

        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}